weights: yolov5s.pt
cfg: models/yolov5s-p2-involution-cbam.yaml
data: TLE.yaml
hyp: data/hyps/hyp.scratch-high.yaml
epochs: 50
batch_size: 8
imgsz: 640
rect: false
resume: false
nosave: true
noval: true
noautoanchor: false
evolve: 4
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: true
sync_bn: false
workers: 4
project: runs/evolve
name: exp
exist_ok: true
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 15
freeze: 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/evolve/exp
